// <auto-generated />
using LPSystemWebAPICore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LPSystemWebAPICore.Migrations
{
    [DbContext(typeof(LPSystemContext))]
    [Migration("20250822205813_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("LPSystemWebAPICore.Models.ApplTable", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("AppStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LoanAmt")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("UserAdhaar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserMob")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AppId", "UserId", "LoanId");

                    b.HasIndex("LoanId");

                    b.HasIndex("UserId");

                    b.ToTable("ApplTable");

                    b.HasData(
                        new
                        {
                            AppId = 1,
                            UserId = 2,
                            LoanId = 1,
                            AppStatus = "Pending",
                            LoanAmt = 50000m,
                            UserAdhaar = "123456789012",
                            UserMob = "9876543210"
                        },
                        new
                        {
                            AppId = 2,
                            UserId = 3,
                            LoanId = 2,
                            AppStatus = "Approved",
                            LoanAmt = 500000m,
                            UserAdhaar = "123456789013",
                            UserMob = "9876543211"
                        });
                });

            modelBuilder.Entity("LPSystemWebAPICore.Models.LoanTable", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LoanAmt")
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("LoanPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LoanROI")
                        .HasColumnType("decimal(18,1)");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LoanId");

                    b.ToTable("LoanTable");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            LoanAmt = 50000m,
                            LoanPeriod = 12,
                            LoanROI = 12.5m,
                            LoanType = "Personal Loan"
                        },
                        new
                        {
                            LoanId = 2,
                            LoanAmt = 500000m,
                            LoanPeriod = 240,
                            LoanROI = 8.5m,
                            LoanType = "Home Loan"
                        },
                        new
                        {
                            LoanId = 3,
                            LoanAmt = 300000m,
                            LoanPeriod = 60,
                            LoanROI = 9.5m,
                            LoanType = "Car Loan"
                        },
                        new
                        {
                            LoanId = 4,
                            LoanAmt = 200000m,
                            LoanPeriod = 48,
                            LoanROI = 10.5m,
                            LoanType = "Education Loan"
                        });
                });

            modelBuilder.Entity("LPSystemWebAPICore.Models.UserTable", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserGender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserTable");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserEmail = "admin@lpsystem.com",
                            UserGender = "Male",
                            UserName = "admin",
                            UserPass = "admin123",
                            UserRole = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            UserEmail = "john@example.com",
                            UserGender = "Male",
                            UserName = "john_doe",
                            UserPass = "password123",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserId = 3,
                            UserEmail = "jane@example.com",
                            UserGender = "Female",
                            UserName = "jane_smith",
                            UserPass = "password123",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserId = 4,
                            UserEmail = "client1@lpsystem.com",
                            UserGender = "Male",
                            UserName = "client1",
                            UserPass = "client123",
                            UserRole = "Client"
                        });
                });

            modelBuilder.Entity("LPSystemWebAPICore.Models.ApplTable", b =>
                {
                    b.HasOne("LPSystemWebAPICore.Models.LoanTable", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LPSystemWebAPICore.Models.UserTable", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
